{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./cron.nix
    ./env.nix
    ./home-manager.nix
    ./hyprland.nix
    ./kernel.nix
    ./mime.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./ssh.nix
    ./rsyslog-forwarding.nix
    ./timezone.nix
    ./user.nix
    ./zram.nix
    ./amneziavpn.nix
    ./power.nix
    ./displayManager.nix
    ./syncthing.nix
    ./docker.nix
    ./udisks.nix
    ./virtualbox.nix
    # ./tailscale.nix
  ];
}
