theme = "cosmic"
close_when_open = true
click_to_close = true
as_window = false
autoplay_videos = false
hide_action_hints_dmenu = true

[placeholders]
default = { input = "Приложения · / файлы · = расчёт · $ окна", list = "Ничего не найдено" }
clipboard = { input = "История копирования", list = "История пуста" }
files = { input = "Найти файл", list = "Файлы не найдены" }
windows = { input = "Перейти к окну", list = "Нет подходящих окон" }
calc = { input = "Введите выражение", list = "Результат появится здесь" }

[providers]
default = ["desktopapplications", "calc"]
empty = ["desktopapplications"]
max_results = 30

[[providers.prefixes]]
prefix = "/"
provider = "files"
[[providers.prefixes]]
prefix = "="
provider = "calc"
[[providers.prefixes]]
prefix = ":"
provider = "clipboard"
[[providers.prefixes]]
prefix = "$"
provider = "windows"
[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[providers.actions]
desktopapplications = [
  { action = "start", label = "Открыть", default = true, bind = "Return" },
  { action = "new_instance", label = "Новое окно", bind = "ctrl Return" },
  { action = "pin", label = "Закрепить", bind = "ctrl p", after = "AsyncReload" },
  { action = "unpin", label = "Открепить", bind = "ctrl p", after = "AsyncReload" },
]
files = [
  { action = "open", label = "Открыть", default = true, bind = "Return" },
  { action = "opendir", label = "Открыть папку", bind = "ctrl Return" },
  { action = "copypath", label = "Копировать путь", bind = "ctrl shift c" },
]
calc = [{ action = "copy", label = "Копировать", default = true, bind = "Return" }]
clipboard = [
  { action = "copy", label = "Копировать", default = true, bind = "Return" },
  { action = "remove", label = "Удалить запись", bind = "ctrl d", after = "AsyncClearReload" },
]
